# Generated by Django 3.2 on 2022-07-17 17:43

from django.db import migrations


class Migration(migrations.Migration):
    def fill_price(apps, schema_editor):
        OrderItem = apps.get_model('foodcartapp', 'OrderItem')
        for item in OrderItem.objects.all().iterator():
            if not item.price:
                item.price = item.product.price
                item.save()

    dependencies = [
        ('foodcartapp', '0041_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(fill_price),
    ]
