# Generated by Django 3.2 on 2022-07-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_order_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Наличные'), (1, 'Электронно')], db_index=True, default=0, verbose_name='способ оплаты'),
        ),
    ]
