# Generated by Django 3.2 on 2022-09-27 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20220902_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Наличные'), (1, 'Электронно')], db_index=True, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodcartapp.order', verbose_name='заказ'),
        ),
    ]
