# Generated by Django 3.2 on 2022-08-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='адрес')),
                ('normalized_address', models.CharField(db_index=True, max_length=150, verbose_name='нормализованый адрес')),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=8, verbose_name='широта')),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=8, verbose_name='долгота')),
                ('timestamp', models.DateTimeField(editable=False, verbose_name='дата обновления')),
            ],
        ),
    ]
