# Generated by Django 3.2 on 2022-09-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoderapp', '0002_auto_20220807_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopoint',
            name='normalized_address',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='нормализованый адрес'),
        ),
    ]
